version: '3.7'

services:
  bot:
   build: "./"
   container_name: bot_container
   restart: always
   volumes:
    - ./:/app/
   ports:
    - 9001:9001 
   command: >
    /bin/sh -c "npm install --production=false
    && npm run dev"